# -*- coding: utf-8 -*-
"""WorldCupPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/AnaSantillanal246102/world-cup-26/blob/C1/WorldCupPrediction.ipynb

# World Cup Prediction 2026


## Objetivo
Campeón del mundo
Equipos que llegan a semifinales
Probabilidad de ganar por selección

##Datos
🔹 Datos de equipos

Ranking FIFA
Elo rating (más preciso que FIFA)
Goles anotados y recibidos
Forma reciente (últimos 10-20 partidos)
Resultados en mundiales anteriores

🔹 Datos de jugadores

Valor de mercado
Goles/asistencias
Lesiones

🔹 Variables de contexto

País anfitrión (USA, México, Canadá)
Clima / sedes
Experiencia en torneos grandes

👉 Fuentes comunes:
FIFA
Transfermarkt
FiveThirtyEight (soccer predictions)
Kaggle datasets

##Metricas nuevas

Promedio de goles
Diferencia de goles
% de victorias

##Links
https://www.kaggle.com/datasets/harrachimustapha/fifa-world-cup-team-dataset

https://www.kaggle.com/datasets/die9origephit/fifa-world-cup-2022-complete-dataset

##Entrada de Datos
"""

!pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests
import random

file_path = "Fifa_world_cup_matches.csv"

# Load the latest version
df_matches = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "die9origephit/fifa-world-cup-2022-complete-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_matches.head())

df_matches.info()

df_matches.describe()

file_path = "test.csv"

# Load the latest version
df_teams = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "harrachimustapha/fifa-world-cup-team-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_teams.head())

df_teams.info()

df_teams.describe()

# Set the path to the file you'd like to load
file_path = "eloratings.csv"

# Load the latest version
df_elo = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "saifalnimri/international-football-elo-ratings",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_elo.head())

df_elo.info()

df_elo.describe()

"""###API FIFA"""

headers = {"Authorization": "Bearer fd_baaa1ff4dab0803ff56630bc5b98d850c2dc4ba0fe7028b3"}

url = "https://footballdata.io/api/v1/fifa-rankings?"

params = {
    "type": "men",
    "page": 1,
    "limit": 50   # intenta traer más equipos por página
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

print(data)
for team in data["data"]:
    print(team["country"]["name"], team["points"]["total"])

"""##MODELO

###Modelo 1
"""

elo_latest = (
    df_elo.sort_values("date")
    .groupby("team")
    .last()
    .reset_index()
)

elo_latest = elo_latest[["team", "rating"]]
elo_latest.rename(columns={"rating": "elo"}, inplace=True)

df = df_teams.merge(elo_latest, on="team", how="left")

df = df_teams.merge(elo_latest, on="team", how="left")

# eliminar equipos sin elo
df = df.dropna(subset=["elo"])

df.head()

df["attack_strength"] = df["goals_scored_last_4y"] / df["goals_scored_last_4y"].mean()
df["defense_strength"] = df["goals_received_last_4y"] / df["goals_received_last_4y"].mean()
epsilon = 1e-6

df["defense_strength"] = df["defense_strength"].replace(0, epsilon)

df["attack_strength"] = df["attack_strength"].clip(0.2, 3)
df["defense_strength"] = df["defense_strength"].clip(0.2, 3)

df.head()

df["win_rate"] = df["wins_last_4y"] / (
    df["wins_last_4y"] + df["draws_last_4y"] + df["losses_last_4y"]
)

df.head()

df["experience"] = df["world_cup_participations_before"] * 0.1
df.head()

df["rating_total"] = (
    0.5 * df["elo"] +
    0.2 * df["fifa_points_pre_tournament"] +
    0.15 * df["win_rate"] * 100 +
    0.1 * df["experience"] * 100 +
    0.05 * (df["squad_total_market_value_eur"] / 1e9)
)
df.head()

avg_goals = (
    df_matches["number of goals team1"].mean() +
    df_matches["number of goals team2"].mean()
) / 2

BASE_GOALS = avg_goals  # normalmente ~1.3–1.6
print("Average goals:",BASE_GOALS)

def get_team_data(team):
    team = team.strip().lower()

    result = df[df["team"] == team]

    if result.empty:
        raise ValueError(f"Equipo no encontrado: {team}")

    return result.iloc[0]

def expected_goals(teamA, teamB):
    A = get_team_data(teamA)
    B = get_team_data(teamB)

    base = BASE_GOALS

    epsilon = 1e-6

    attack_A = max(A["attack_strength"], epsilon)
    defense_B = max(B["defense_strength"], epsilon)

    attack_B = max(B["attack_strength"], epsilon)
    defense_A = max(A["defense_strength"], epsilon)

    lambda_A = base * (attack_A / defense_B)
    lambda_B = base * (attack_B / defense_A)

    # ajuste Elo
    elo_factor = np.exp((A["elo"] - B["elo"]) / 400)

    lambda_A *= elo_factor
    lambda_B /= elo_factor

    # ✅ asegurar valores válidos
    lambda_A = max(lambda_A, 0.05)
    lambda_B = max(lambda_B, 0.05)

    # ✅ evitar infinitos o NaN
    lambda_A = np.nan_to_num(lambda_A, nan=0.5, posinf=3, neginf=0.5)
    lambda_B = np.nan_to_num(lambda_B, nan=0.5, posinf=3, neginf=0.5)

    return lambda_A, lambda_B

print(df[["team", "elo", "attack_strength", "defense_strength"]].head())

def simulate_match(teamA, teamB):
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    return goals_A, goals_B

def knockout_match(teamA, teamB):
    goals_A, goals_B = simulate_match(teamA, teamB)

    # usar modelo híbrido SIEMPRE
    winner = hybrid_winner(teamA, teamB, goals_A, goals_B)

    return winner

def simulate_round(team_list):
    teams = team_list.copy()
    random.shuffle(teams)

    winners = []

    # si hay número impar, uno pasa automáticamente
    if len(teams) % 2 == 1:
        winners.append(teams.pop())

    for i in range(0, len(teams), 2):
        winners.append(knockout_match(teams[i], teams[i+1]))

    return winners

teams_list = df["team"].tolist()

def simulate_tournament():
    current = teams_list.copy()

    while len(current) > 2:
        current = simulate_round(current)

    final1, final2 = current
    champion = knockout_match(final1, final2)

    return champion, final1, final2

from collections import Counter

N = 10000

champions = []
finalists = []

for _ in range(N):
    champ, f1, f2 = simulate_tournament()
    champions.append(champ)
    finalists.extend([f1, f2])

# 1. precalcular
ml_probs = {}
teams = df["team"].tolist()

for teamA in teams:
    for teamB in teams:
        if teamA != teamB:
            ml_probs[(teamA, teamB)] = ml_win_probability(teamA, teamB)

# 2. simulación

N = 1000

champions = []

for _ in range(N):
    champ, _, _ = simulate_tournament()
    champions.append(champ)

champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Finalistas:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")

champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Finalistas:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")

"""###Modelo Machine Learning"""

# quitar % y convertir a float
df_matches["possession team1"] = df_matches["possession team1"].str.replace('%', '').astype(float)
df_matches["possession team2"] = df_matches["possession team2"].str.replace('%', '').astype(float)

from sklearn.ensemble import RandomForestClassifier

# features
X = df_matches[[
    "possession team1",
    "possession team2",
    "total attempts team1",
    "total attempts team2",
    "passes team1",
    "passes team2"
]]

# target
y = (df_matches["number of goals team1"] > df_matches["number of goals team2"]).astype(int)

model = RandomForestClassifier()
model.fit(X, y)

from sklearn.ensemble import RandomForestClassifier

# features
X = df_matches[[
    "possession team1",
    "possession team2",
    "total attempts team1",
    "total attempts team2",
    "passes team1",
    "passes team2"
]].copy()

# diferencias (MUY importante)
X["possession_diff"] = X["possession team1"] - X["possession team2"]
X["attempts_diff"] = X["total attempts team1"] - X["total attempts team2"]

# target
y = (df_matches["number of goals team1"] > df_matches["number of goals team2"]).astype(int)

# limpiar datos
X = X.apply(pd.to_numeric, errors='coerce')
X = X.fillna(X.mean())

# entrenar
model = RandomForestClassifier(
n_estimators=50,  # antes 200
    max_depth=5,
    random_state=42
)
model.fit(X, y)

def ml_win_probability(teamA, teamB):
    A = get_team_data(teamA)
    B = get_team_data(teamB)

    # features simuladas desde dataset equipos
    poss_A = A["win_rate"] * 100
    poss_B = B["win_rate"] * 100

    attempts_A = A["attack_strength"] * 10
    attempts_B = B["attack_strength"] * 10

    passes_A = A["win_rate"] * 500
    passes_B = B["win_rate"] * 500

    X_new = pd.DataFrame([{
        "possession team1": poss_A,
        "possession team2": poss_B,
        "total attempts team1": attempts_A,
        "total attempts team2": attempts_B,
        "passes team1": passes_A,
        "passes team2": passes_B,
        "possession_diff": poss_A - poss_B,
        "attempts_diff": attempts_A - attempts_B
    }])

    prob = model.predict_proba(X_new)[0][1]
    return prob

def hybrid_winner(teamA, teamB, goals_A, goals_B):
    prob_ml = ml_win_probability(teamA, teamB)

    # probabilidad Poisson implícita
    prob_poisson = 1 if goals_A > goals_B else 0

    # mezcla
    alpha = 0.7  # peso Poisson
    combined_prob = alpha * prob_poisson + (1 - alpha) * prob_ml

    return teamA if random.random() < combined_prob else teamB

def hybrid_winner(teamA, teamB, goals_A, goals_B):
    prob_ml = ml_probs.get((teamA, teamB), 0.5)

    diff = goals_A - goals_B
    prob_poisson = 1 / (1 + np.exp(-diff))

    alpha = 0.6
    combined = alpha * prob_poisson + (1 - alpha) * prob_ml

    return teamA if random.random() < combined else teamB

def simulate_match(teamA, teamB):
    # Poisson (goles)
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    # ML (probabilidad)
    prob_ml = ml_win_probability(teamA, teamB)

    # combinación híbrida
    if goals_A == goals_B:
        # desempate con ML
        if random.random() < prob_ml:
            goals_A += 1
        else:
            goals_B += 1

    return goals_A, goals_B

"""###Modelo Prueba"""

import numpy as np
import random
from collections import Counter

# -------------------------------
# 1. Equipos y ratings
# -------------------------------
teams = {
    "Argentina": 2050,
    "Francia": 2000,
    "Brasil": 1980,
    "Inglaterra": 1950,
    "España": 1920,
    "Portugal": 1900,
    "Alemania": 1850,
    "México": 1750
}

team_list = list(teams.keys())

# -------------------------------
# 2. Convertir Elo → fuerza ofensiva
# -------------------------------
def expected_goals(teamA, teamB):
    eloA = teams[teamA]
    eloB = teams[teamB]

    base_goals = 1.5  # promedio mundial

    attack_strength_A = 10 ** ((eloA - 1500) / 400)
    defense_strength_B = 10 ** ((eloB - 1500) / 400)

    lambda_A = base_goals * (attack_strength_A / defense_strength_B)

    # lo mismo para B
    attack_strength_B = 10 ** ((eloB - 1500) / 400)
    defense_strength_A = 10 ** ((eloA - 1500) / 400)

    lambda_B = base_goals * (attack_strength_B / defense_strength_A)

    if teamA == "México":
      lambda_A *= 1.1

    return lambda_A, lambda_B

# -------------------------------
# 3. Simular marcador con Poisson
# -------------------------------
def simulate_match(teamA, teamB):
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    return goals_A, goals_B

# -------------------------------
# 4. Partido knockout (con penales)
# -------------------------------
def knockout_match(teamA, teamB):
    goals_A, goals_B = simulate_match(teamA, teamB)

    if goals_A > goals_B:
        return teamA
    elif goals_B > goals_A:
        return teamB
    else:
        # empate → penales (50/50)
        return random.choice([teamA, teamB])

# -------------------------------
# 5. Simular ronda
# -------------------------------
def simulate_round(teams):
    random.shuffle(teams)
    winners = []

    for i in range(0, len(teams), 2):
        teamA = teams[i]
        teamB = teams[i+1]
        winner = knockout_match(teamA, teamB)
        winners.append(winner)

    return winners

# -------------------------------
# 6. Simular torneo completo
# -------------------------------
def simulate_tournament():
    current = team_list.copy()

    while len(current) > 2:
        current = simulate_round(current)

    # Final
    finalist1, finalist2 = current
    champion = knockout_match(finalist1, finalist2)

    return champion, finalist1, finalist2

# -------------------------------
# 7. Monte Carlo
# -------------------------------
N = 10000

champions = []
finalists = []

for _ in range(N):
    champ, f1, f2 = simulate_tournament()
    champions.append(champ)
    finalists.extend([f1, f2])

# -------------------------------
# 8. Resultados
# -------------------------------
champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Probabilidad de campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Probabilidad de ser finalista:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")